// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using whm.Models;

#nullable disable

namespace whm.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260817001314_SeedRoles")]
    partial class SeedRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QRValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("whm.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLog_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLog_Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("AuditLog_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("whm.Models.Bin", b =>
                {
                    b.Property<int>("Bin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Bin_Id"));

                    b.Property<string>("Bin_Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Bin_Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bin_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Shelf_Id")
                        .HasColumnType("integer");

                    b.HasKey("Bin_Id");

                    b.HasIndex("Shelf_Id");

                    b.ToTable("Bins");
                });

            modelBuilder.Entity("whm.Models.Categories", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Category_Id"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Department_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Category_Id");

                    b.HasIndex("Department_Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("whm.Models.Department", b =>
                {
                    b.Property<int>("Department_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Department_Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Department_Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("whm.Models.Report", b =>
                {
                    b.Property<int>("Report_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Report_Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Product_Id")
                        .HasColumnType("integer");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Warehouse_Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("craeteByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Report_Id");

                    b.HasIndex("Product_Id");

                    b.HasIndex("Warehouse_Id");

                    b.HasIndex("craeteByUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("whm.Models.ReportSchedule", b =>
                {
                    b.Property<int>("ReportSchedule_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportSchedule_Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Product_Id")
                        .HasColumnType("integer");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("RunAt")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Warehouse_Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("craeteByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("ReportSchedule_Id");

                    b.HasIndex("Product_Id");

                    b.HasIndex("Warehouse_Id");

                    b.HasIndex("craeteByUserId");

                    b.ToTable("ReportSchedules");
                });

            modelBuilder.Entity("whm.Models.Role", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Role_Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Role_Id");

                    b.HasIndex("Role_Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Role_Id = 1,
                            CreateAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Role_Description = "System Administrator",
                            Role_Name = "Admin",
                            UpdateAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Role_Id = 2,
                            CreateAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Role_Description = "Normal Employee",
                            Role_Name = "Employee",
                            UpdateAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Role_Id = 3,
                            CreateAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Role_Description = "Warehouse Manager",
                            Role_Name = "Manager",
                            UpdateAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("whm.Models.Room", b =>
                {
                    b.Property<int>("Room_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Room_Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Room_Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Room_Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Room_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Warehouse_Id")
                        .HasColumnType("integer");

                    b.HasKey("Room_Id");

                    b.HasIndex("Warehouse_Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("whm.Models.Row", b =>
                {
                    b.Property<int>("Row_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Row_Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Room_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Row_Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Row_Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Row_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Row_Id");

                    b.HasIndex("Room_Id");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("whm.Models.Shelf", b =>
                {
                    b.Property<int>("Shelf_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Shelf_Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Row_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Shelf_Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Shelf_Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Shelf_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Shelf_Id");

                    b.HasIndex("Row_Id");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("whm.Models.Stock", b =>
                {
                    b.Property<int>("Stock_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Stock_Id"));

                    b.Property<int>("Bin_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Stock_Id");

                    b.HasIndex("Bin_Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("whm.Models.Transaction", b =>
                {
                    b.Property<int>("transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("transaction_Id"));

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FromBinId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Product_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int?>("ToBinId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<int>("Unit_Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("transaction_Id");

                    b.HasIndex("FromBinId");

                    b.HasIndex("Product_Id");

                    b.HasIndex("ToBinId");

                    b.HasIndex("Unit_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("whm.Models.Unit", b =>
                {
                    b.Property<int>("Unit_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Unit_Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit_Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Unit_Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("whm.Models.Users", b =>
                {
                    b.Property<Guid>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("User_Id");

                    b.HasIndex("Role_Id");

                    b.HasIndex("User_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("whm.Models.Warehouse", b =>
                {
                    b.Property<int>("Warehouse_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Warehouse_Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Warehouse_Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Warehouse_Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Warehouse_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Warehouse_Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("whm.Models.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("whm.Models.Unit", "Units")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("whm.Models.AuditLog", b =>
                {
                    b.HasOne("whm.Models.Users", "Users")
                        .WithMany("auditLog")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("whm.Models.Bin", b =>
                {
                    b.HasOne("whm.Models.Shelf", "Shelf")
                        .WithMany("Bins")
                        .HasForeignKey("Shelf_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("whm.Models.Categories", b =>
                {
                    b.HasOne("whm.Models.Department", "Department")
                        .WithMany("Categories")
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("whm.Models.Report", b =>
                {
                    b.HasOne("Product", "Products")
                        .WithMany("reports")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("whm.Models.Warehouse", "Warehouses")
                        .WithMany("reports")
                        .HasForeignKey("Warehouse_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("whm.Models.Users", "CreateByUser")
                        .WithMany("Reports")
                        .HasForeignKey("craeteByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Products");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("whm.Models.ReportSchedule", b =>
                {
                    b.HasOne("Product", "Products")
                        .WithMany("reportSchedules")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("whm.Models.Warehouse", "Warehouses")
                        .WithMany("reportSchedules")
                        .HasForeignKey("Warehouse_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("whm.Models.Users", "CreateByUser")
                        .WithMany("reportSchedules")
                        .HasForeignKey("craeteByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Products");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("whm.Models.Room", b =>
                {
                    b.HasOne("whm.Models.Warehouse", "Warehouse")
                        .WithMany("Rooms")
                        .HasForeignKey("Warehouse_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("whm.Models.Row", b =>
                {
                    b.HasOne("whm.Models.Room", "Room")
                        .WithMany("Rows")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("whm.Models.Shelf", b =>
                {
                    b.HasOne("whm.Models.Row", "Row")
                        .WithMany("Shelves")
                        .HasForeignKey("Row_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Row");
                });

            modelBuilder.Entity("whm.Models.Stock", b =>
                {
                    b.HasOne("whm.Models.Bin", "Bin")
                        .WithMany("Stocks")
                        .HasForeignKey("Bin_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany("Stock")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bin");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("whm.Models.Transaction", b =>
                {
                    b.HasOne("whm.Models.Bin", "FromBin")
                        .WithMany("Fromtransactions")
                        .HasForeignKey("FromBinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Product", "Product")
                        .WithMany("transactions")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("whm.Models.Bin", "ToBin")
                        .WithMany("Totransactions")
                        .HasForeignKey("ToBinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("whm.Models.Unit", "Unit")
                        .WithMany("transactions")
                        .HasForeignKey("Unit_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("whm.Models.Users", "User")
                        .WithMany("transactions")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromBin");

                    b.Navigation("Product");

                    b.Navigation("ToBin");

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("whm.Models.Users", b =>
                {
                    b.HasOne("whm.Models.Role", "role")
                        .WithMany("User")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Stock");

                    b.Navigation("reportSchedules");

                    b.Navigation("reports");

                    b.Navigation("transactions");
                });

            modelBuilder.Entity("whm.Models.Bin", b =>
                {
                    b.Navigation("Fromtransactions");

                    b.Navigation("Stocks");

                    b.Navigation("Totransactions");
                });

            modelBuilder.Entity("whm.Models.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("whm.Models.Department", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("whm.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("whm.Models.Room", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("whm.Models.Row", b =>
                {
                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("whm.Models.Shelf", b =>
                {
                    b.Navigation("Bins");
                });

            modelBuilder.Entity("whm.Models.Unit", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("transactions");
                });

            modelBuilder.Entity("whm.Models.Users", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("auditLog");

                    b.Navigation("reportSchedules");

                    b.Navigation("transactions");
                });

            modelBuilder.Entity("whm.Models.Warehouse", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("reportSchedules");

                    b.Navigation("reports");
                });
#pragma warning restore 612, 618
        }
    }
}
